M48
; DRILL file {KiCad 7.0.2} date Sat Sep 23 11:44:03 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-23T11:44:03-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X138.2Y-60.3
X138.2Y-69.3
T2
X106.94Y-53.0
X106.94Y-65.0
X106.94Y-67.0
X106.94Y-79.0
T3
X120.0Y-44.0
X120.0Y-86.0
T0
M30
