M48
; DRILL file {KiCad 9.0.3} date 2025-08-10T22:23:36-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-10T22:23:36-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0335
%
G90
G05
T1
X4.8594Y-3.1488
X5.087Y-3.1488
T2
X6.2185Y-3.4675
X6.2185Y-3.8848
M30
